Form/DataTransformer/StringToEntity.php
<?php

namespace Sherlockode\AdvancedContentBundle\Form\DataTransformer;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\PropertyAccess\PropertyAccess;

class StringToEntity implements DataTransformerInterface
{
    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @var string
     */
    private $entityClass;

    /**
     * @var string
     */
    private $identifierField;

    /**
     * @param EntityManagerInterface $oe
     * @param string                 $entityClass
     * @param string                 $identifierField
     */
    public function __construct(EntityManagerInterface $em, $entityClass, $identifierField)
    {
        $this->em = $em;
        $this->entityClass = $entityClass;
        $this->identifierField = $identifierField;
    }

    /**
     * Transforms a string into an entity
     *
     * @param string $valueAsString
     *
     * @return object|null
     */
    public function transform($valueAsString)
    {
        if (empty($valueAsString)) {
            return null;
        }

        $entity = $this->em->getRepository($this->entityClass)->findOneBy([
            $this->identifierField => $valueAsString,
        ]);

        return $entity;
    }

    /**
     * Transforms an entity into a string
     *
     * @param object $entity
     *
     * @return string
     */
    public function reverseTransform($entity)
    {
        if (empty($entity)) {
            return null;
        }

        $propertyAccessor = PropertyAccess::createPropertyAccessor();

        return $propertyAccessor->getValue($entity, $this->identifierField);
    }
}

Form/Type/AcbContentType.php
<?php

namespace Sherlockode\AdvancedContentBundle\Form\Type;

use Doctrine\ORM\EntityManagerInterface;
use Sherlockode\AdvancedContentBundle\Manager\ConfigurationManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

class AcbContentType extends AbstractType
{
    /**
     * @var ConfigurationManager
     */
    private $configurationManager;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @param ConfigurationManager   $configurationManager
     * @param EntityManagerInterface $em
     */
    public function __construct(ConfigurationManager $configurationManager, EntityManagerInterface $em)
    {
        $this->configurationManager = $configurationManager;
        $this->em = $em;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $contents = $this->em->getRepository($this->configurationManager->getEntityClass('content'))->findBy([
            'page' => null,
        ], ['slug' => 'ASC']);
        $slugs = [];
        foreach ($contents as $content) {
            $slugs[$content->getSlug()] = $content->getSlug();
        }

        $builder
            ->add('content', ChoiceType::class, [
                'label' => false,
                'choices' => $slugs,
            ])
        ;
    }
}

Form/Type/AcbFileType.php
<?php

namespace Sherlockode\AdvancedContentBundle\Form\Type;

use Sherlockode\AdvancedContentBundle\Event\AcbFilePreSubmitEvent;
use Sherlockode\AdvancedContentBundle\Manager\MimeTypeManager;
use Sherlockode\AdvancedContentBundle\Manager\UploadManager;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;

class AcbFileType extends AbstractType
{
    /**
     * @var UploadManager
     */
    private $uploadManager;

    /**
     * @var EventDispatcherInterface
     */
    private $eventDispatcher;

    /**
     * @var MimeTypeManager
     */
    private $mimeTypeManager;

    /**
     * @param UploadManager            $uploadManager
     * @param EventDispatcherInterface $eventDispatcher
     * @param MimeTypeManager          $mimeTypeManager
     */
    public function __construct(UploadManager $uploadManager, EventDispatcherInterface $eventDispatcher, MimeTypeManager $mimeTypeManager)
    {
        $this->uploadManager = $uploadManager;
        $this->eventDispatcher = $eventDispatcher;
        $this->mimeTypeManager = $mimeTypeManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $mimeTypeChoices = $options['mime_types'] ?? $this->mimeTypeManager->generateMimeTypeChoices();

        $builder
            ->add('title', TextType::class, [
                'label' => 'field_type.file.title',
                'constraints' => !$options['required'] ? [] : [
                    new NotBlank(null, null, null, null, $options['validation_groups']),
                ],
            ])
            ->add('mime_type', ChoiceType::class, [
                'label' => 'field_type.file.restriction_type',
                'multiple' => true,
                'choices' => is_array($mimeTypeChoices) ? $mimeTypeChoices : [],
                'choice_attr' => function ($choice): array {
                    return ['data-mime-type' => json_encode($this->mimeTypeManager->getMimeTypesByCode($choice))];
                },
                'attr' => ['data-mime-type-restriction' => '']
            ])
        ;

        $builder->addEventListener(
            FormEvents::POST_SET_DATA,
            function (FormEvent $event) use ($options) {
                $form = $event->getForm();
                $data = $event->getData();
                if (!is_array($data)) {
                    $data = [];
                }

                $this->updateForm($form, $data, $options);
            }
        );

        $builder->addEventListener(
            FormEvents::PRE_SUBMIT,
            function (FormEvent $event) use ($options) {
                $data = $event->getData();
                $form = $event->getForm();

                if (!empty($data['delete'])) {
                    if (!empty($data['src'])) {
                        $this->uploadManager->remove($data['src']);
                        unset($data['src']);
                    }
                    unset($data['delete']);
                }

                if (!empty($data['file'])) {
                    $fileName = $this->uploadManager->getFileName($data['file']);
                    $this->eventDispatcher->dispatch(
                        new AcbFilePreSubmitEvent($data['file'], $fileName),
                        AcbFilePreSubmitEvent::NAME
                    );

                    $data['src'] = $fileName;
                    $this->updateForm($form, $data, $options, true);
                } elseif (isset($data['src'])) {
                    $this->updateForm($form, $data, $options);
                }

                $event->setData($data);
            }
        );
        $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
            $data = $event->getData();
            $form = $event->getForm();
            if ($form->getConfig()->getCompound()) {
                $cleanData = [];
                // clean data to prevent saving empty fields
                foreach ($form as $key => $child) {
                    if (isset($data[$key])) {
                        $cleanData[$key] = $data[$key];
                    }
                }

                $event->setData($cleanData);
            }
        });
    }

    /**
     * @param FormInterface $form
     * @param array         $data
     * @param array         $options
     * @param bool          $hasFile
     *
     * @return void
     */
    private function updateForm(FormInterface $form, $data, $options, $hasFile = false)
    {
        if (!isset($data['src'])) {
            $data['src'] = '';
        }

        $isFileUploaded = $this->uploadManager->isFileUploaded($data['src']) || $hasFile;

        $hasNotBlankConstraint = false;
        foreach ($options['file_constraints'] as $constraint) {
            if ($constraint instanceof NotBlank) {
                $hasNotBlankConstraint = true;
                break;
            }
        }

        if (false === $hasNotBlankConstraint && true === $options['required'] && false === $isFileUploaded) {
            $options['file_constraints'][] = new NotBlank(null, null, null, null, $options['validation_groups']);
        }

        $mimeTypes = $options['mime_types_constraint'];
        if (!empty($data['mime_type'])) {
            $mimeTypes = [];

            foreach ($data['mime_type'] as $type) {
                $mimeTypes[] = $this->mimeTypeManager->getMimeTypesByCode($type);
            }

            $mimeTypes = array_merge([], ...$mimeTypes);
        }
        $options['file_constraints'][] = new File(null, null, null, $mimeTypes);

        $form
            ->add('file', FileType::class, [
                'label' => 'field_type.file.file',
                'required' => !$isFileUploaded && $options['required'],
                'constraints' => $options['file_constraints'],
                'attr' => ['data-mime-type-restriction' => '']
            ])
        ;

        if ($isFileUploaded) {
            $form
                ->add('delete', CheckboxType::class, [
                    'label' => 'field_type.file.delete',
                    'required' => false,
                ])
                ->add('src', HiddenType::class, [
                    'required' => $options['required'],
                ])
            ;
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'translation_domain' => 'AdvancedContentBundle',
            'file_constraints' => [],
            'mime_types' => null,
            'mime_types_constraint' => $this->mimeTypeManager->getAllMimeTypes(),
        ]);
    }

    /**
     * Make the image accessible in view
     *
     * @param FormView      $view    The view
     * @param FormInterface $form    The form
     * @param array         $options The options
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $fileSrc = $form->getData()['src'] ?? '';
        if ('' !== $fileSrc && false === $this->uploadManager->isFileUploaded($fileSrc)) {
            $fileSrc = '';
        }

        $view->vars['uploadManager'] = $this->uploadManager;
        $view->vars['src'] = $fileSrc;
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'acb_file';
    }
}

Form/Type/ColumnType.php
<?php

namespace Sherlockode\AdvancedContentBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

class ColumnType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $sizeOptions = [
            'layout_type.column.config.sizes.1_column' => 1,
            'layout_type.column.config.sizes.2_column' => 2,
            'layout_type.column.config.sizes.3_column' => 3,
            'layout_type.column.config.sizes.4_column' => 4,
            'layout_type.column.config.sizes.5_column' => 5,
            'layout_type.column.config.sizes.6_column' => 6,
            'layout_type.column.config.sizes.7_column' => 7,
            'layout_type.column.config.sizes.8_column' => 8,
            'layout_type.column.config.sizes.9_column' => 9,
            'layout_type.column.config.sizes.10_column' => 10,
            'layout_type.column.config.sizes.11_column' => 11,
            'layout_type.column.config.sizes.12_column' => 12,
            'layout_type.column.config.sizes.column' => '-',
            'layout_type.column.config.sizes.column_auto' => 'auto',
        ];

        $offsetOptions = [
            'layout_type.column.config.offsets.no_offset' => 0,
            'layout_type.column.config.offsets.1_column' => 1,
            'layout_type.column.config.offsets.2_column' => 2,
            'layout_type.column.config.offsets.3_column' => 3,
            'layout_type.column.config.offsets.4_column' => 4,
            'layout_type.column.config.offsets.5_column' => 5,
            'layout_type.column.config.offsets.6_column' => 6,
            'layout_type.column.config.offsets.7_column' => 7,
            'layout_type.column.config.offsets.8_column' => 8,
            'layout_type.column.config.offsets.9_column' => 9,
            'layout_type.column.config.offsets.10_column' => 10,
            'layout_type.column.config.offsets.11_column' => 11,
        ];

        $builder
            ->add('size', ChoiceType::class, [
                'label' => 'layout_type.column.config.size',
                'choices' => $sizeOptions,
                'required' => true,
            ])
            ->add('offset', ChoiceType::class, [
                'label' => 'layout_type.column.config.offset',
                'choices' => $offsetOptions,
                'placeholder' => false,
                'required' => false,
            ])
            ->add('size_sm', ChoiceType::class, [
                'label' => 'layout_type.column.config.size',
                'choices' => $sizeOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
            ->add('offset_sm', ChoiceType::class, [
                'label' => 'layout_type.column.config.offset',
                'choices' => $offsetOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
            ->add('size_md', ChoiceType::class, [
                'label' => 'layout_type.column.config.size',
                'choices' => $sizeOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
            ->add('offset_md', ChoiceType::class, [
                'label' => 'layout_type.column.config.offset',
                'choices' => $offsetOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
            ->add('size_lg', ChoiceType::class, [
                'label' => 'layout_type.column.config.size',
                'choices' => $sizeOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
            ->add('offset_lg', ChoiceType::class, [
                'label' => 'layout_type.column.config.offset',
                'choices' => $offsetOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
            ->add('size_xl', ChoiceType::class, [
                'label' => 'layout_type.column.config.size',
                'choices' => $sizeOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
            ->add('offset_xl', ChoiceType::class, [
                'label' => 'layout_type.column.config.offset',
                'choices' => $offsetOptions,
                'placeholder' => 'layout_type.column.config.inherit_from_smaller',
                'required' => false,
            ])
        ;
    }

    public function getBlockPrefix()
    {
        return 'acb_column_config';
    }
}

Form/Type/ContentDataType.php
<?php

namespace Sherlockode\AdvancedContentBundle\Form\Type;

use Symfony\Component\Form\AbstractType;

class ContentDataType extends AbstractType
{
    public function getParent()
    {
        return ElementsType::class;
    }

    public function getBlockPrefix()
    {
        return 'acb_content_data';
    }
}

Form/Type/ElementAdvancedType.php
<?php

namespace Sherlockode\AdvancedContentBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class ElementAdvancedType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('class', TextType::class, [
                'label' => 'configuration.advanced.class',
                'required' => false,
            ])
            ->add('id', TextType::class, [
                'label' => 'configuration.advanced.id',
                'required' => false,
            ])
            ->add('hide_on', ElementHideOnType::class, [
                'label' => 'configuration.advanced.hide_on',
                'required' => false,
            ])
        ;
    }
}

Resources/views/Form/base_theme.html.twig
{% extends acb_base_form_theme() %}

Resources/views/Form/common.html.twig
{% extends '@SherlockodeAdvancedContent/Form/theme.html.twig' %}

{% trans_default_domain 'AdvancedContentBundle' %}

{% block acb_simple_collection %}
    {% set button_label = button_label|default('content.add_field') %}
    {%- set attr = attr|default([]) -%}
    {% if prototype is defined %}
        {% set entryForm = prototype %}
        {%- set attr = attr|merge({'data-prototype': block('acb_collection_entry') }) -%}
    {% endif %}
    {%- set attr = attr|merge({'class': 'acb-sortable-group' }) -%}
    <div {{ block('widget_container_attributes') }}>
        {% for child in form %}
            {% set entryForm = child %}
            {{ block('acb_collection_entry') }}
        {% endfor %}
    </div>
    {% if allow_add|default(false) %}
        {{ block('acb_add_item_button') }}
    {% endif %}
{% endblock %}

{% macro acb_collection_entry(form) %}
    {% set entryForm = form %}
    {{ block('acb_collection_entry') }}
{% endmacro %}

{% block acb_collection_entry %}
    <div class="acb-field field-row acb-row acb-sortable">
        <div class="panel-heading">
            <span class="panel-title">
                {% if entryForm.vars.panel_label is defined %}
                    {{ entryForm.vars.panel_label|trans }}
                {% else %}
                #<span class="panel-position">{{ entryForm.vars.name|number_format + 1 }}</span>
                {% endif %}
            </span>
            {{- block('acb_panel_actions') -}}
        </div>
        <div class="panel-body">
            {{- form_widget(entryForm) -}}
        </div>
    </div>
{% endblock %}

{% block acb_add_item_button %}
    <button type="button"
            class="acb-add-collection-item"
            data-list="#{{ form.vars.id }}"
            data-type="{{ type }}"
            aria-label="{{ button_label|trans }}">
        <i class="fa-solid fa-plus"></i>
    </button>
{% endblock %}

{% block acb_panel_actions %}
    <div class="field-actions">
        {% if allowEdit is not defined or allowEdit == true %}
            <button type="button" class="acb-edit-row" title="{{ 'edit'|trans }}">
                <i class="fa-solid fa-pencil"></i>
            </button>
            <button type="button" class="acb-duplicate-row" title="{{ 'duplicate'|trans }}">
                <i class="fa-solid fa-copy"></i>
            </button>
        {% endif %}
        {% if allowDelete is not defined or allowDelete == true %}
            <button type="button" class="acb-remove-row" title="{{ 'delete'|trans }}" data-confirm-delete="{{ 'delete_confirm'|trans }}">
                <i class="fa-solid fa-trash-can"></i>
            </button>
        {% endif %}
    </div>
{% endblock %}

Resources/views/Form/theme.html.twig
{% extends '@SherlockodeAdvancedContent/Form/base_theme.html.twig' %}

{% trans_default_domain 'AdvancedContentBundle' %}

{% block form_row %}
    {% if form.parent and form.vars.compound and (form.parent.vars.name == 'value' or (form.parent.parent and form.parent.parent.vars.name == 'value')) %}
        {% set row_attr = row_attr|default({})|merge({'class': row_attr.class|default('') ~ ' acb-field-element-compound'}) %}
    {% endif %}
    {{ parent() }}
{% endblock %}

{% block collection_widget %}
    <div class="acb-collection-widget">
        <div class="acb-collection-list" {% if prototype is defined %}data-prototype="{{ form_widget(form.vars.prototype)|e('html_attr') }}"{% endif %}>
            {% for child in form %}
                {{ form_widget(child) }}
            {% endfor %}
        </div>
        {% if form.vars.allow_add %}
            <button type="button" class="btn btn-secondary btn-add-acb-collection" title="{{ 'collection_add_item'|trans }}">
                <i class="fa fa-plus"></i> {{ 'collection_add_item'|trans }}
            </button>
        {% endif %}
    </div>
{% endblock collection_widget %}

{% block collection_entry_widget %}
    <div class="acb-collection-item">
        {{ form_widget(form) }}
        {% if form.parent.vars.allow_delete %}
            <button type="button" class="btn btn-danger btn-remove-acb-collection" title="{{ 'collection_remove_item'|trans }}">
                <i class="fa fa-trash"></i> {{ 'collection_remove_item'|trans }}
            </button>
        {% endif %}
    </div>
{% endblock %}